name: mukawwin_3
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rflutter_alert: ^2.0.7
  flutter_staggered_animations: ^1.1.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  image_cropper: ^8.0.2
  image_picker: ^1.0.0
  permission_handler: ^11.0.0
  http: ^1.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - icons/
    - icons/list.png
    - icons/profile.png
    - icons/scan.png

  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Lato-Regular.ttf
